version: '3.7'
services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - FROM_TWILIO_NUMBER=${FROM_TWILIO_NUMBER}
      - USER_NUMBER=${USER_NUMBER}
    volumes:
      - ./n8n_data:/home/node/.n8n